name: 'Slack'
description: 'Sends the build status to a Slack webhook.'
inputs:
  webhook:
    description: 'The Slack webhook URL'
    required: true
  job-status:
    description: 'The status of the current job.'
    required: true
  text:
    description: 'The text part of the slack message.'
    required: false
runs:
  using: 'node12'
  main: 'action.js'
